version: '3.7'
services:
  apache:
    build:
      context: .
      dockerfile: docker/Dockerfile.apache
    container_name: php-apache
    volumes:
      - .:/var/www/html
    ports:
      - 5555:80
  socket:
    build:
      context: .
      dockerfile: docker/Dockerfile.socket
    container_name: php-socket
    ports:
      - 5556:80
    depends_on:
      - apache