FROM node:18

# Install nodemon
RUN npm install -g nodemon

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY ./api/socket/ ./

RUN npm install

EXPOSE 80

ENTRYPOINT [ "node", "." ]