on:
  push:
    branches:
    - main
    - master
    - release/*
    
jobs:
  deploy:
    name: Deploy to BLUEMOON
    runs-on: ubuntu-22.04
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: unnecessary
      - 
        name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      -
        name: Deploy with rsync
        run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/workspaces/iim/iimersive
      -
        name: Stop previous Docker container
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker stop iimersive"
      -
        name: Remove previous Docker container
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker rm iimersive"
      -
        name: Rebuild Docker image
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker build -t php-apache-iimersive ."
      -
        name: Restart Docker container
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker run -d --name iimersive -p 8010:80 --mount type=bind,source=\"$(pwd)\",target=/var/www/html php-apache-iimersive"
